//
//  BgGradients+asHexes.swift
//  Animation Examples
//
//  Created by Bekzhan Talgat on 12.02.2024.
//

import UIKit


extension BgGradients {
    
    var asHexes: [String] {
        switch self {
        
        /// red
        case .eveningShine:                 return ["#b92b27", "#1565C0"]
        case .watchingHour:                 return ["#c31432", "#240b36"]
        case .flare:                        return ["#f12711", "#f5af19"]
        case .burningOrange:                return ["#FF416C", "#FF4B2B"]
        case .byDesign:                     return ["#009FFF", "#ec2F4B"]
        case .wireTap:                      return ["#8A2387", "#E94057", "#F27121"]
        case .sinCityRed:                   return ["#ED213A", "#93291E"]
        case .vanusa:                       return ["#DA4453", "#89216B"]
        case .pureLast:                     return ["#333333", "#dd1818"]
        case .bighead:                      return ["#c94b4b", "#4b134f"]
        case .relaxingRed:                  return ["#fffbd5", "#b20a2c"]
        case .alive: 	                    return ["#CB356B", "#BD3F32"]
        case .compareNow:                   return ["#EF3B36", "#FFFFFF"]
        case .coal:                         return ["#EB5757", "#000000"]
        case .loveAndLiberity:              return ["#200122", "#6f0000"]
        case .ibizaSunset:                  return ["#ee0979", "#ff6a00"]
        case .bloodRed:                     return ["#f85032", "#e73827"]
        case .fireWatch:                    return ["#cb2d3e", "#ef473a"]
        case .minimalRed:                   return ["#F00000", "#DC281E"]
        case .sweetMorning:                 return ["#FF5F6D", "#FFC371"]
        case .netflix:                      return ["#8E0E00", "#1F1C18"]
        case .poncho:                       return ["#403A3E", "#BE5869"]
        case .passion:                      return ["#e53935", "#e35d5b"]
        case .instagram:                    return ["#833ab4", "#fd1d1d", "#fcb045"]
        case .redMist:                      return ["#000000", "#e74c3c"]
        case .theStrain:                    return ["#870000", "#190A05"]
        
        /// orange
        case .tfOrange:                     return ["#f5af4c", "#f15929"]
        case .citrusPeal:                   return ["#fdc830", "#f37335"]
        case .orangeFun:                    return ["#fc4a1a", "#f7b733"]
        case .lightOrange:                  return ["#ffb75e", "#ed8f03"]
        case .darkKnight:                   return ["#ba8b02", "#181818"]
        case .masterCard:                   return ["#f46b45", "#eea849"]
        case .soundCloud:                   return ["#fe8c00", "#f83600"]
        case .kyoto:                        return ["#c21500", "#ffc500"]
        case .sunrise:                      return ["#ff512f", "#f09819"]
        case .mango:                        return ["#ffe259", "#ffa751"]
        case .blooker20:                    return ["#e65c00", "#f9d423"]
        case .dawn:                         return ["#f3904f", "#3b4371"]
            
        /// yellow
        case .anwar:                        return ["#334d50", "#cbcaa5"]
        case .alihossein:                   return ["#f7ff00", "#db36a4"]
        case .sulphur:                      return ["#CAC531", "#F3F9A7"]
        case .sagePersuasion:               return ["#CCCCB2", "#757519"]
        case .snapchat:                     return ["#fffc00", "#ffffff"]
        case .freshTurbocent:               return ["#f1f2b5", "#135058"]
        case .siriusTamed:                  return ["#efefbb", "#d4d3dd"]
        case .frozen:                       return ["#403b4a", "#e7e9bb"]
        case .rea:                          return ["#ffe000", "#799f0c"]
        case .vasily:                       return ["#e9d362", "#333333"]
            
        /// blue
        case .coolBlues:                    return ["#2193b0", "#6dd5ed"]
        case .moonlightAsteroid:            return ["#0F2027", "#203A43", "#2C5364"]
        case .coolSky:                      return ["#2980B9", "#6DD5FA", "#2C5364"]
        case .azureLane:                    return ["#7F7FD5", "#86A8E7", "#91EAE4"]
        case .blueRespberry:                return ["#00B4DB", "#0083B0"]
        case .eveningNight:                 return ["#005AA7", "#FFFDE4"]
        case .digitalWater:                 return ["#74ebd5", "#ACB6E5"]
        case .hydrogen:                     return ["#667db6", "#0082c8", "#0082c8", "#667db6"]
        case .telegram:                     return ["#1c92d2", "#f2fcfe"]
        case .scooter:                      return ["#36D1DC", "#5B86E5"]
        case .visionsOfGrandeur:            return ["#000046", "#1CB5E0"]
        case .blueSkies:                    return ["#56CCF2", "#2F80ED"]
        case .maldives:                     return ["#B2FEFA", "#0ED2F7"]
        case .cocoaIce:                     return ["#c0c0aa", "#1cefff"]
        case .jodhpur:                      return ["#9CECFB", "#65C7F7", "#0052D4"]
        case .frost:                        return ["#000428", "#004e92"]
        case .deapSeaSpace:                 return ["#2C3E50", "#4CA1AF"]
        case .solidVault:                   return ["#3a7bd5", "#3a6073"]
        case .brightVault:                  return ["#00d2ff", "#928DAB"]
        case .decent:                       return ["#4CA1AF", "#C4E0E5"]
        case .drakSkies:                    return ["#4B79A1", "#283E51"]
        case .nightHawk:                    return ["#2980b9", "#2c3e50"]
        case .clearSky:                     return ["#005C97", "#363795"]
        case .betweenSkyAndNight:           return ["#2c3e50", "#3498db"]
        case .facebookManager:              return ["#00c6ff", "#0072ff"]
        case .reef:                         return ["#00d2ff", "#3a7bd5"]
        case .aqualicious:                  return ["#50C9C3", "#96DEDA"]
        case .steller:                      return ["#7474BF", "#348AC7"]
        case .mantle:                       return ["#24C6DC", "#514A9D"]
        case .boraBora:                     return ["#2BC0E4", "#EAECC6"]
        case .veniceBlue:                   return ["#085078", "#85D8CE"]
        case .mirage:                       return ["#16222A", "#3A6073"]
        case .stripe:                       return ["#1FA2FF", "#12D8FA", "#A6FFCB"]
        case .aquaMarine:                   return ["#1A2980", "#26D0CE"]
        case .nimvelo:                      return ["#314755", "#26a0da"]
        case .seeBlue:                      return ["#2b5876", "#4e4376"]
        case .sexyBlue:                     return ["#2193b0", "#6dd5ed"]
        case .skyline:                      return ["#1488CC", "#2B32B2"]
        case .blu:                          return ["#00416A", "#E4E5E6"]
        case .horizon:                      return ["#003973", "#E5E5BE"]
        case .royal:                        return ["#141e30", "#243b55"]
            
        /// green
        case .harvey:                       return ["#1f4037", "#99f2c8"]
        case .summerDog:                    return ["#a8ff78", "#78ffd6"]
        case .quepal:                       return ["#11998e", "#38ef7d"]
        case .subu:                         return ["#0cebeb", "#20e3b2", "#29ffc6"]
        case .chittyBang:                   return ["#007991", "#78ffd6"]
        case .cinnaMint:                    return ["#4AC29A", "#BDFFF3"]
        case .pacificDream:                 return ["#34e89e", "#0f3443"]
        case .orca:                         return ["#44A08D", "#093637"]
        case .theBlueLagoon:                return ["#43C6AC", "#191654"]
        case .underTheLake:                 return ["#093028", "#237A57"]
        case .honeyDew:                     return ["#43C6AC", "#F8FFAE"]
        case .disco:                        return ["#4ECDC4", "#556270"]
        case .vine:                         return ["#00bf8f", "#001510"]
        case .endlessRiver:                 return ["#43cea2", "#185a9d"]
        case .betweenClouds:                return ["#73C8A9", "#373B44"]
        case .seeBlizz:                     return ["#1CD8D2", "#93EDC7"]
        case .mojito:                       return ["#1D976C", "#93F9B9"]
        case .seeWeed:                      return ["#4CB8C4", "#3CD3AD"]
        case .greenBeach:                   return ["#02AAB0", "#00CDAC"]
        case .windy:                        return ["#acb6e5", "#86fde8"]
        case .terminal:                     return ["#000000", "#0f9b0f"]
        case .behongo:                      return ["#52c234", "#061700"]
        case .moss:                         return ["#134E5E", "#71B280"]
        case .greenToDark:                  return ["#6A9113", "#141517"]
                
        /// pink
        case .azurePop:                     return ["#ef32d9", "#89fffd"]
        case .candy:                        return ["#D3959B", "#BFE6BA"]
        case .sublimeLight:                 return ["#fc5c7d", "#6a82fb"]
        case .cosmicFusion:                 return ["#ff00cc", "#333399"]
        case .dusk:                         return ["#2c3e50", "#fd746c"]
        case .yoda:                         return ["#ff0099", "#493240"]
        case .neuromancer:                  return ["#f953c6", "#b91d73"]
        case .shifter:                      return ["#bc4e9c", "#f80759"]
        case .pinkFlavour:                  return ["#800080", "#ffc0cb"]
        case .argon:                        return ["#03001e", "#7303c0", "#ec38bc", "#fdeff9"]
        case .blackRose:                    return ["#f4c4f3", "#fc67fa"]
        case .flicker:                      return ["#ff0084", "#33001b"]
        case .cherryblossom:                return ["#fbd3e9", "#bb377d"]
        case .dimigo:                       return ["#ec008c", "#fc6767"]
        
        /// purple
        case .purplerBliss:                 return ["#360033", "#0b8793"]
        case .shroomHaze:                   return ["#5C258D", "#4389A2"]
        case .twitch:                       return ["#6441a5", "#2a0845"]
        case .friday:                       return ["#83a4d4", "#b6fbff"]
        case .deepPurple:                   return ["#673ab7", "#512da8"]
        case .amin:                         return ["#8e2de2", "#4a00e0"]
        case .keyMeh:                       return ["#8360c3", "#2ebf91"]
        case .magic:                        return ["#59c173", "#a17fe0", "#5d26c1"]
        case .kyooTah:                      return ["#544a7d", "#ffd452"]
        case .ultraViolet:                  return ["#654ea3", "#eaafc8"]
        case .slightOceanView:              return ["#a8c0ff", "#3f2b96"]
        case .moonPurple:                   return ["#4e54c8", "#8f94fb"]
        case .lawrencium:                   return ["#0f0c29", "#302b63", "#24243e"]
        case .delicate:                     return ["#d3cce3", "#e9e4f0"]
        case .relay:                        return ["#3a1c71", "#d76d77", "#ffaf7b"]
        case .venice:                       return ["#6190e8", "#a7bfe8"]
        case .canYouFeelTheLoveTonight:     return ["#4568dc", "#b06ab3"]
        case .radar:                        return ["#a770ef", "#cf8bf3", "fdb99b"]
        case .amethyst:                     return ["#9d50bb", "#6e48aa"]
        case .dirtyFog:                     return ["#b993d6", "#8ca6db"]
        case .kashmir:                      return ["#614385", "#516395"]
        case .purpleParadise:               return ["#1d2b64", "#f8cdda"]
        
        /// gray
        case .winter:                       return ["#E6DADA", "#274046"]
        case .moor:                         return ["#616161", "#9bc5c3"]
        case .sky:                          return ["#076585", "#ffffff"]
        case .lizard:                       return ["#304352", "#d7d2cc"]
        case .foreverLost:                  return ["#5D4157", "#A8CABA"]
        case .petrol:                       return ["#BBD2C5", "#536976"]
        case .fiftyShadesOfGray:            return ["#bdc3c7", "#2c3e50"]
        case .gradeGray:                    return ["#bdc3c7", "#2c3e50"]
        case .sandToBlue:                   return ["#3e5151", "#decba4"]
        case .zinc:                         return ["#ada996", "#f2f2f2", "#dbdbdb", "#eaeaea"]
        case .selenium:                     return ["#3c3b3f", "#605c3c"]
        case .deepSpace:                    return ["#000000", "#434343"]
        case .portrait:                     return ["#8e9eab", "#eef2f3"]
        case .hersheys:                     return ["#1e130c", "#9a8478"]
        case .serveQuick:                   return ["#485563", "#29323c"]
        case .ash:                          return ["#606c88", "#3f4c6b"]
        case .titanium:                     return ["#283048", "#859398"]
        case .midnightCity:                 return ["#232526", "#414345"]
        case .mystic:                       return ["#757f9a", "#d7dde8"]
        case .steelGray:                    return ["#1f1c2c", "#928dab"]
        case .copper:                       return ["#b79891", "#94716b"]
            
        }
    }
    
}

